name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # Humnay pichli baar cache lagaya tha, ho sakta hai cache mein purani corrupted dependency phansi ho.
    # Is baar hum baghair cache k direct fresh npm install krwa rahay hain.
    - name: Clean Install Dependencies
      run: npm ci

    - name: Run Unit Tests with Global Jest
      run: npx jest --forceExit